name: "Github Workflow IAC AWS Account"

on:
  workflow_call:
    inputs:
      message_body:
        description: "Customized message body you want to send if you don't want to send the default message."
        type: string
        required: true
      sa_name:
        description: "Name of storage account holding the deployment scripts"
        type: string
        required: true
    secrets:
      ARM_ENVIRONMENT:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      BIT_CSB_SSH_PRIVATE_KEY:
        required: true


jobs:
  iac_aws_accounts:
    name: "IAC for AWS Accounts"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BIT_CSB_SSH_PRIVATE_KEY: ${{ secrets.BIT_CSB_SSH_PRIVATE_KEY }}
      TF_VAR_sa_name: ${{ inputs.sa_name }}
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v3
        with:
          path: "iac-aws-accounts"

      - name: Checkout github-iac-aws-accounts
        uses: actions/checkout@v3
        with:
          repository: "bit-csb/github-iac-aws-accounts"
          path: "github-iac-aws-accounts"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Perform Invititations
        uses: bit-csb/github-azuread-invitation@v3
        with:
          map-file: "./iac-aws-accounts/creation/accounts.tf"
          map-name: "account_map"
          users-property: "owners"
          message_body: "${{ inputs.message_body }}"

      - name: Copy files
        shell: bash
        run: |
          cp ./iac-aws-accounts/creation/*.tf ./github-iac-aws-accounts/terraform/creation/
          cp ./iac-aws-accounts/environment/backend-creation.tfvars ./github-iac-aws-accounts/terraform/creation/backend.tfvars
          cp ./iac-aws-accounts/environment/variables-creation.tfvars ./github-iac-aws-accounts/terraform/creation/variables.tfvars

          mv ./iac-aws-accounts/configuration/*.tf ./github-iac-aws-accounts/terraform/configuration/
          cp ./iac-aws-accounts/environment/backend-configuration.tfvars ./github-iac-aws-accounts/terraform/configuration/backend.tfvars
          cp ./iac-aws-accounts/environment/variables-configuration.tfvars ./github-iac-aws-accounts/terraform/configuration/variables.tfvars

      - name: Configure ssh
        uses: bit-csb/github-configure-ssh@v2
        with:
          privateSshKey: $BIT_CSB_SSH_PRIVATE_KEY

      - name: Ensure account count does not decrease
        shell: bash
        run: |
          typeset -i currentCount=$(grep -E "^\s*(bit-aws-.*.tf|aws_(t|i|p)_[[:alnum:]]{8}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{12})\s*=\s*\{$" creation/accounts.tf -c)
          typeset -i previousCount=$(cat counter)
          if [ "$currentCount" -lt "$previousCount" ]; then
            >&2 echo "Number of accounts: currentCount $currentCount must not be lower than previousCount $previousCount"
            exit 1
          else
            echo "$currentCount" > counter
          fi

      - name: Create AWS Accounts
        uses: bit-csb/github-terraform-flow@v3
        with:
          directory: "./github-iac-aws-accounts/terraform/creation"
          backend-config: "backend.tfvars"
          var-file: "variables.tfvars"

      - name: Ensure account count does not decrease
        shell: bash
        run: |
          typeset -i currentCount=$(ls -1 ./github-iac-aws-accounts/terraform/configuration | grep -E "^(bit-aws-.*.tf|aws_(t|i|p)_[[:alnum:]]{8}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{12}.tf)$" -c)
          typeset -i previousCount=$(cat counter)
          if [ "$currentCount" -lt "$previousCount" ]; then
            >&2 echo "Number of accounts: currentCount $currentCount must not be lower than previousCount $previousCount"
            exit 1
          else
            echo "$currentCount" > counter
          fi

      - name: Configure AWS Accounts
        uses: bit-csb/github-terraform-flow@v3
        with:
          directory: "./github-iac-aws-accounts/terraform/configuration"
          backend-config: "backend.tfvars"
          var-file: "variables.tfvars"

      - name: Copy files configuration files back
        shell: bash
        run: |
          cp ./github-iac-aws-accounts/terraform/configuration/*.tf ./iac-aws-accounts/configuration/

      - name: Remove Non-Configuration files
        shell: bash
        working-directory: ./iac-aws-accounts/configuration
        run: |
          rm -f main.tf provider.tf terraform.tf variables.tf

      - name: Update iac repo
        shell: bash
        working-directory: ./iac-aws-accounts
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "The following files in the folder ./configuration have changed:";
            git status --porcelain
            git pull origin main

            git config user.name 'Github Workflow'
            git config user.email 'csb@bit.admin.ch'
            git remote set-url origin git@github-bit-csb:$GITHUB_REPOSITORY
            git add --all
            git commit -m "Update of counter after terraform apply for ./creation"
            git push origin main

          else
            echo "no changes";
          fi
